MovieRatings/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieRatingsDB;

namespace MovieRatings.Controllers
{
    public class RatingController : Controller
    {
        // GET: Rating
        public ActionResult Index()
        {
            var cust = DB.GetMovies();
            ViewBag.Movies = cust;
            return View();
        }

        public ActionResult Detail(int id)
        {
            //get model from database
            ViewBag.Movie = DB.GetRating(id);
            return View();
        }
    }
}

MovieRatings/Views/Rating/Detail.cshtml
@using MovieRatingsDB;
@model Rating

@{
    ViewBag.Title = "Detail";
}

@{ Rating rating = ViewBag.movie }

<h2>Detail</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => rating.RatingId)
        </dt>

        <dd>
            @Html.DisplayFor(model => rating.Stars)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => rating.Note)
        </dt>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

MovieRatings/Views/Rating/Index.cshtml
@using MovieRatingsDB;
@model Movie
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@{
    List<Movie> movies = ViewBag.Movies;
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MovieId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieReleaseDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in movies)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MovieId)
            </td>
            <td>
                <a href="@Url.Action("Detail", "Rating",new { id=item.MovieId })">@Html.DisplayFor(modelItem => item.MovieTitle)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MovieReleaseDate)
            </td>
        </tr>
    }


</table>

MovieRatings/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>